#kibana
#
#VERSION 0.0.1

FROM moonnoon/base:testing
MAINTAINER Fei Lee <lee.lfff@gmail.com>

RUN git clone https://github.com/elasticsearch/kibana.git /opt/kibana

EXPOSE 80
WORKDIR /opt/kibana/
#CMD []
